---

services:
  docker-nas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-nas
    environment:
      - USERNAME=${USERNAME}
      - VOLUME=${VOLUME}
    volumes:
      - ${VOLUME}
    ports:
      - "8080:5000"
    networks:
      - nas-network

volumes:
  - ${VOLUME}

networks:
  nas-network:
    driver: bridge
      
