---

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-nas
    restart: unless-stopped
    environment:
      - VOLUME=${VOLUME}
      - HOST_PATH=${HOST_PATH}
    volumes:
      - ${HOST_PATH}:${VOLUME}
      - data:/data:rw
    ports:
      - "8080:5000"
    networks:
      - nas-network

volumes:
  nas: 
  data:

networks:
  nas-network:
    driver: bridge
      
