---

services:
  webgui:
    build:
      context: .
      dockerfile: Dockerfile.webgui
    container_name: notion-webgui
    environment:
      - USERNAME=${USERNAME}
      - VOLUME=${VOLUME}
    volumes:
      - ${VOLUME}
    ports:
      - "8080:5000"
    networks:
      - nas-network

volumes:
  ${VOLUME}

networks:
  nas-network:
    driver: bridge
      
