---

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-nas
    restart: unless-stopped
    environment:
      - VOLUME=${VOLUME}
      - HOST_PATH=${HOST_PATH}
    volumes:
      - ${HOST_PATH}:${VOLUME}
      - data:/data:rw
    ports:
      - "8080:5000"
    networks:
      - nas-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: docker-nas-nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./static:/app/static
    networks:
      - nas-network
    depends_on:
      - web

volumes:
  nas: 
  data:

networks:
  nas-network:
    driver: bridge
      
