---

services:
  docker-nas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-nas
    environment:
      - USERNAME=${USERNAME}
      - VOLUME=${VOLUME}
    volumes:
      - nas:${VOLUME}
    ports:
      - "8080:5000"
    networks:
      - nas-network
volumes:
  nas: 

networks:
  nas-network:
    driver: bridge
      
